# Generated by Django 4.2.11 on 2024-05-05 16:56

from django.db import migrations, models
import django.utils.timezone
import products.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('image', models.ImageField(upload_to='your_upload_path', validators=[products.models.validate_image_dimensions])),
                ('description', models.CharField(max_length=100)),
                ('sub_title', models.CharField(default=None, max_length=200, null=True)),
                ('time_spent', models.CharField(default=None, max_length=100)),
                ('Brochure', models.FileField(default=None, null=True, upload_to='your_upload_path', validators=[products.models.validate_pdf_extension])),
                ('About', models.TextField(null=True)),
                ('Visit', models.TextField(null=True)),
                ('Tours', models.TextField(null=True)),
                ('Programs', models.TextField(null=True)),
                ('Image_bk_1', models.ImageField(upload_to='your_upload_path')),
                ('Image_bk_2', models.ImageField(upload_to='your_upload_path')),
                ('Image_bk_3', models.ImageField(upload_to='your_upload_path')),
                ('is_active', models.BooleanField(default=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
